### ISSUE TITLE
Is help output in console the MarkDown format? If so, can we display it nicely?

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JunoLab/atom-julia-client#223]
When I type "? " on console and enter some function name, say, fft, I get the following output starting with \`\`\`. So, I figured that the help output is in the MarkDown format. But in the julia console in the atom editor, it simply displays with \`\`\` and the help document is not displayed in the MarkDown way. Is this behavior expected? Or I can display such help output in a nicer way? I would appreciate any help!  Thanks a lot!

**Comment by pfitzseb** [comment]
This is already (kinda) fixed in a newer version of Atom.jl:
![md](https://cloud.githubusercontent.com/assets/6735977/18145629/5c1ca6a8-6fcc-11e6-95c8-ec963b107277.PNG)
Latex rendering would be nice though...

**Comment by BoundaryValueProblems** [comment]
Thanks! I just updated Atom Editor to 1.10.0 and Atom package under julia v.0.4.5. Yet, it doesn't display as yours in the proper Markdown way. Which version of Atom.jl are you talking about, and how to get it? Pkg.update() does not update Atom.jl at this point.
Thanks!

**Comment by pfitzseb** [comment]
Oh right, should've clarified: Newer *unreleased* version ;) Sorry.

**Comment by pfitzseb** [comment]
New version is released -- update and you should be good to go.

**Comment by BoundaryValueProblems** [comment]
Hi, pfitzeb.
I just updated julia-client to 0.5.5. It still does not display as MarkDown. Can you tell me how to toggle the help output to MarkDown?
Also with this new version, after each command execution, it generates the following warning:
WARNING: Atom.jl: unrecognised message clearLazy.
Thanks for your help!

**Comment by BoundaryValueProblems** [comment]
Hi, pfitzeb.
OK, I also upgraded julia itself to 0.5.0 from 0.4.6. Then, the MD stuff started working!
Thanks for putting this nice functionality in julia-client!
Best,
BVPs

**Comment by pfitzseb** [comment]
Great, glad you figured it out (I meant to answer you, but obviously forgot to -- sorry!).
