### ISSUE TITLE
REPL extremely slow after update to julia-client 0.6.13

### ISSUE THREAD

**Issue by jibaneza** [JunoLab/atom-julia-client#481]
Scrolling in the REPL is extremely slow after the update. If I change it to the legacy style it behaves normally.
I tried uninstalling and installing Atom again and the problem persists.

I am using OS X High Sierra.

**Comment by pfitzseb** [comment]
Okay, can you try the following in a terminal after closing all Atom instances:
```
apm remove ink
apm remove julia-client

apm install ink
apm install julia-client
```
That will reinstall both packages but should leave all settings intact.

I'm pretty sure nothing changed in the latest julia-client update that should affect terminal performance at all -- it is however possible that the ink update introduced that regression since we updated the package that provides the terminal. If the reinstallation doesn't help performance then you might could also try
```
apm install ink@0.8.4
apm install julia-client@0.6.12
```
to revert to the old versions temporarily.

**Comment by jibaneza** [comment]
Thank you for the tips!
Now I’m more confused, I tried uninstalling and installing, downgrading one at a time and downgrading both ink and julia-client one version and the problem persists in all cases.

Writing and scrolling in REPL is slow, the rest is ok. Changing to legacy style solves the problem.

El 25 jun 2018, a las 13:33, Sebastian Pfitzner <notifications@github.com<mailto:notifications@github.com>> escribió:


Okay, can you try the following in a terminal after closing all Atom instances:

apm remove ink
apm remove julia-client

apm install ink
apm install julia-client


That will reinstall both packages but should leave all settings intact.

I'm pretty sure nothing changed in the latest julia-client update that should affect terminal performance at all -- it is however possible that the ink update introduced that regression since we updated the package that provides the terminal. If the reinstallation doesn't help performance then you might could also try

apm install ink@0.8.4
apm install julia-client@0.6.12


to revert to the old versions temporarily.

**Comment by pfitzseb** [comment]
Is it possible you update your graphics drivers or something like that in the same time period? The new REPL being fast relies on good GPU support.

**Comment by jibaneza** [comment]
No, I don't think I have updated anything else. I was pretty convinced it was the julia-client update since it happened immediately after that. I opened Atom, it asked me to confirm the update and after that it became slow. Now, seeing that the issue remains after downgrading versions I have no idea what it can be. Not a big issue for me if I can use the legacy version without problems.

**Comment by vjamsa** [comment]
I'm having same problem with the julia REPL on atom. I updated graphics drivers, reinstalled atom etc. and still the REPL has like 5 seconds delay when typing something. Legacy works fine and fast, but I really need to get the REPL working.

**Comment by dominusmi** [comment]
Same problem on my end, also started after a julia-client update and the downgrade isn't fixing it

**Comment by pfitzseb** [comment]
I still suspect this happens because of the GPU renderer not working well on your machines. 
Fortunately, the next version of xterm.js (which we'll ship as soon as possible) will include an option to use a DOM based fallback renderer, which should hopefully fix those issues.

The performance regression is kinda worrying but I'm not entirely sure what to do about it. If you feel like it then you could try the following:

- go to `~/.atom/packages/ink`
- open `package.json`, search for `xterm` and change the version entry to some something like `^3.0.0`, `^3.1.0`, or `^3.4.0`.
- call `apm install` (in the `ink` dir)
- restart Atom and check terminal performance

That's a bit annoying though for something that will probably/hopefully be fixed in the next release, but it might offer a short term solution.

**Comment by vjamsa** [comment]
Changing xterm to 3.0.0, 3.1.0 or 3.4.0 didn't help in my end.

**Comment by pfitzseb** [comment]
Hm, very weird.

I think I just experienced a similar problem though -- Electron's (and therefore Atom's) rendering sometimes breaks when my Laptop wakes up from sleeping, which makes the REPL super slow (but also causes black rendering artifacts and stuff like that). Everything works fine after restarting Atom though.

**Comment by s-broda** [comment]
I have the same issue. As soon as I as much as place the cursor in the REPL, CPU usage skyrockets with Atom maxing out an entire core, and the REPL is almost entirely unresponsive, with a 5 second input lag for every character. Reinstalling packages and Atom itself does not help.

**Fix**:
For me, it seems the issue started when Atom updated itself to 1.28.0 (this is on Windows). Downgrading Atom to 1.27.2 by downloading the zip file from [here](https://github.com/atom/atom/releases) fixes the problem.

**Comment by pfitzseb** [comment]
That kinda makes sense since Atom updated to Electron 2.0 on that release. I'll look into releasing a version of Juno that uses xterm.js 3.5, which offers an option to switch to a fallback DOM renderer which should be relatively performant regardless.

**Comment by pfitzseb** [comment]
Next version will have an option to enable the fallback renderer (which at least for me fixes the performance problems).
