### ISSUE TITLE
Failed to activate the julia-client package

### ISSUE THREAD

**Issue by danielchen26** [JunoLab/atom-julia-client#642]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.11.2

### Stack Trace

Failed to activate the julia-client package

```
At Cannot find module '../build/Debug/pty.node'

Error: Cannot find module '../build/Debug/pty.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at Object.loadNative (/packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/utils.js:22:16)
    at /packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/unixTerminal.js:24:19)
    at /packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/unixTerminal.js:255:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/index.js:14:20)
    at /packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/index.js:52:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/julia-client/lib/connection/process/basic.js:3:24)
    at /packages/julia-client/lib/connection/process/basic.js:186:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/julia-client/lib/connection/process/cycler.coffee:2:9)
    at /packages/julia-client/lib/connection/process/cycler.coffee:1:1)
    at /packages/julia-client/lib/connection/process/cycler.coffee:1:1)
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
atom-dark-fusion-syntax 2.2.1 
atom-django 0.3.2 
atom-html-preview 0.2.6 
atom-latex 0.8.11 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-mdtoc 0.8.4 
atom-runner 2.7.1 
atom-ternjs 0.20.0 
atom-typescript 13.3.0 
atomatigit 1.5.5 
autoclose-html 0.23.0 
autocomplete-bibtex 1.2.7 
autocomplete-html-entities 0.2.0 
autocomplete-modules 2.3.0 
autocomplete-paths 2.12.2 
autocomplete-python 1.16.0 
autoprefixer 4.1.0 
autoupdate-packages 1.3.1 
blame 1.1.0 
busy 0.7.0 
busy-signal 2.0.1 
css-snippets 1.1.0 
diagrams 0.30.0 
docblockr 0.13.7 
easy-motion-redux 1.3.3 
emmet 2.4.3 
ex-mode 0.18.0 
expand-region 0.5.0 
file-icons 2.1.36 
fixmyjs 1.4.1 
git-history 3.3.0 
git-log 0.4.1 
git-plus 8.7.1 
git-time-machine 2.1.0 
gitkraken-bisect 0.1.1 
glowing-cursor 0.1.2 
golden-ratio 0.3.0 
highlight-line 0.12.0 
highlight-selected 0.16.0 
Hydrogen 2.13.0 
hydrogen-python 0.0.8 
hyperclick 0.1.5 
indent-detective 0.4.0 
ink 0.11.5 
intentions 1.1.5 
javascript-snippets 1.2.1 
julia-client 0.11.2 
language-diff 0.7.0 
language-julia 0.19.1 
language-latex 1.2.0 
language-markdown 0.37.0 
language-matlab 0.2.1 
language-weave 0.6.5 
latex 0.50.2 
latex-completions 0.3.6 
latexer 0.3.0 
lines 0.13.1 
linter 2.3.1 
linter-bootlint 1.1.7 
linter-csslint 2.0.6 
linter-eslint 8.5.5 
linter-jshint 3.1.17 
linter-julia 0.7.4 
linter-markdown 5.2.10 
linter-ui-default 1.8.0 
linter-xmllint 1.4.4 
markdown-pdf 2.2.0 
markdown-scroll-sync 2.1.2 
markdown-toc 0.4.2 
markdown-writer 2.11.9 
maximize-panes 0.2.0 
merge-conflicts 1.4.5 
move-panes 0.2.0 
neon-syntax 0.3.7 
nucleus-dark-ui 0.12.3 
pdf-view 0.72.0 
pigments 0.40.2 
platformio-ide-terminal 2.9.4 
project-plus 1.0.0 
proton-mode 0.16.0 
python-isort 0.0.7 
python-tools 0.6.9 
python-yapf 0.14.0 
react 0.18.0 
react-snippets 1.2.0 
recent-files-fuzzy-finder 1.0.0 
relative-numbers 0.9.0 
release-notes 0.53.0 
remote-ftp 2.2.2 
script 3.18.1 
tab-switcher 1.5.6 
teletype 0.13.4 
theme-switch 0.6.0 
tool-bar 1.2.0 
uber-juno 0.3.0 
vim-mode-plus 1.36.2 
zentabs 0.8.9 
```

**Comment by Ales999** [comment]
Same this error after upgrade today Atom to v.141.0 x64 (osx Mojave)

**Comment by pfitzseb** [comment]
Yup, also see our [FAQ](http://docs.junolab.org/latest/man/faq/).

**Comment by MikeInnes** [comment]
FWIW, I don't think this is an issue addressed by the FAQ; there's no option to rebuild here so it's not obvious that the package needs to be re-installed.

<img width="1115" alt="Screenshot 2019-10-24 13 01 31" src="https://user-images.githubusercontent.com/2234614/67483771-68f8b800-f65e-11e9-9fa3-67354e8aca71.png">

**Comment by pfitzseb** [comment]
Mh, true.
Not sure why Atom isn't recognizing julia-client as having native deps that need to be rebuilt, but we might be able to catch this ourselves.

**Comment by pierre-haessig** [comment]
I was hit by this issue after updagrading to Atom 1.41.0 on Linux Debian.

I tried to uninstall/restart/reinstall julia-client, as recommended by @Ales999, but the reinstallation failed

```
Installing “julia-client@0.11.2” failed.Hide output…

> @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3 install /tmp/apm-install-dir-119924-5935-1oqex6y.ozqw/node_modules/julia-client/node_modules/@pfitzseb/node-pty-prebuilt
> prebuild-install || node scripts/install.js


Aborted
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/usr/share/atom/resources/app/apm/bin/python-interceptor.sh" is v3.7.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:501:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:282:7)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:380:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:596:12)
gyp ERR! System Linux 4.19.0-6-amd64
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-119924-5935-1oqex6y.ozqw/node_modules/julia-client/node_modules/@pfitzseb/node-pty-prebuilt
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
Aborted
Aborted
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-119924-5935-1oqex6y.ozqw/package.json'
npm WARN apm-install-dir-119924-5935-1oqex6y.ozqw No description
npm WARN apm-install-dir-119924-5935-1oqex6y.ozqw No repository field.
npm WARN apm-install-dir-119924-5935-1oqex6y.ozqw No README data
npm WARN apm-install-dir-119924-5935-1oqex6y.ozqw No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pierre/.atom/.apm/_logs/2019-10-24T12_13_38_833Z-debug.log
```

Here is the debug log file: [2019-10-24T12_13_38_833Z-debug.log](https://github.com/JunoLab/atom-julia-client/files/3767425/2019-10-24T12_13_38_833Z-debug.log)

**Comment by pfitzseb** [comment]
What does `atom -v` return for you?

**Comment by pierre-haessig** [comment]
Here are the version numbers:
```
$ atom -v
Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

**Comment by pfitzseb** [comment]
Hm, that looks fine, and I can install julia-client on my Arch machine without any issues.

**Comment by lwhitefox** [comment]
I didn't modify my Mac OS X machine (OS 10.14.6) but I got hit by this this morning when restarting Atom.  

As implied above I just did the command line amp uninstall/install for Julia-client and I'm up and running  again

**Comment by braamvandyk** [comment]
After the update to 1.41.0 on Windows 10, it is impossible on either of my machines to install julia-client, hence the normal procedure of `apm uninstall julia-client` followed by `apm install julia-client` actually killed my setup.

**Comment by johncwok** [comment]
Uninstalling and re-installing didn't work for me. Is there an alternative to the ```julia-client``` package that I could use ?

**Comment by pfitzseb** [comment]
No. What error message are you getting?

**Comment by johncwok** [comment]
I get this :

```Failed to activate the julia-client package

Cannot read property 'fromId' of undefined
Hide Stack Trace
TypeError: Cannot read property 'fromId' of undefined
    at Object.activate (file:///C:/Users/cnelias/.atom/packages/julia-client/lib/runtime/outline.js:12:22)
    at Object.consumeInk (file:///C:/Users/cnelias/.atom/packages/julia-client/lib/runtime.coffee:33:11)
    at Object.consumeInk (file:///C:/Users/cnelias/.atom/packages/julia-client/lib/julia-client.coffee:120:7)
    at Provider.provide (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:14:1125283)
    at ServiceHub.consume (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3308657)
    at Package.activateServices (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3316889)
    at Package.activateNow (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3313644)
    at measure (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3312968)
    at Package.measure (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3310578)
    at activationPromise.activationPromise.Promise (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3312828)
    at new Promise (<anonymous>)
    at Package.activate (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3312771)
    at PackageManager.activatePackage (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:382554)
    at config.transactAsync (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:382170)
    at Config.transactAsync (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:331818)
    at PackageManager.activatePackages (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:382120)
    at PackageManager.activate (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:381670)
    at t.loadState.then (C:\Users\cnelias\AppData\Local\atom\ap```

**Comment by pfitzseb** [comment]
Sounds like ink isn't properly installed. Try re-installing that as well.

**Comment by kschertler** [comment]
After updating Atom to version 1.41.0, I have exactly the same problem as described here by @pierre-haessig - but I am on macOS. `apm install julia-client` fails with the same errors. Also tried reinstalling ink before - no change.

**Comment by pfitzseb** [comment]
I released a new version of julia-client (as well as ink) a couple of minutes ago (which might or might not help with this issue). Can you all try the following steps again:
1. Close *all* Atom instances.
2. Open a terminal and type in `apm uninstall ink` and `apm uninstall julia-client`,
3. Re-install those packages with `apm install ink`, followed by `apm install julia-client`.
4. Open Atom.

**Comment by kschertler** [comment]
Uninstalling and re-installing of `ink` worked. But re-installing (the already uninstalled) julia-client by `apm install julia-client` again ends up in:

```
> node-pty-prebuilt-multiarch@0.9.0 install /private/var/folders/zl/msgtt7313v358s645pskd1080000gn/T/apm-install-dir-119928-29294-upfwuw.v1m/node_modules/julia-client/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js


prebuild-install WARN install read ECONNRESET
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.7.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:501:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:282:7)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:380:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:596:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/zl/msgtt7313v358s645pskd1080000gn/T/apm-install-dir-119928-29294-upfwuw.v1m/node_modules/julia-client/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/zl/msgtt7313v358s645pskd1080000gn/T/apm-install-dir-119928-29294-upfwuw.v1m/package.json'
npm WARN apm-install-dir-119928-29294-upfwuw.v1m No description
npm WARN apm-install-dir-119928-29294-upfwuw.v1m No repository field.
npm WARN apm-install-dir-119928-29294-upfwuw.v1m No README data
npm WARN apm-install-dir-119928-29294-upfwuw.v1m No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/schertler_k/.atom/.apm/_logs/2019-10-28T15_58_59_390Z-debug.log
```

**Comment by pfitzseb** [comment]
What's the output of `atom -v` in a terminal?

**Comment by kschertler** [comment]
I get:
```
$ atom -v
Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

**Comment by EduardoCarias** [comment]
> Sounds like ink isn't properly installed. Try re-installing that as well.

I had the same issue. This worked for me

**Comment by togo59** [comment]
Just accepting all the updates and the advised restart worked for me. Ubuntu 16.04,
`$ atom -v
Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
`

**Comment by kschertler** [comment]
Could successfully reinstall the julia-client on macOS with the proposed apm uninstall/install process - but had to do `conda deactivate` before.

**Comment by johncwok** [comment]
I tried re-installing the ink package but now I get the following error ```Tried to create a gutter with a name that is already in use.
Hide Stack Trace
Error: Tried to create a gutter with a name that is already in use.
    at GutterContainer.addGutter (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:564470)
    at TextEditor.addGutter (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:49406)
    at BreakpointManager.init (file:///C:/Users/cnelias/.atom/packages/ink/lib/debugger/breakpoints.js:103:8)
    at file:///C:/Users/cnelias/.atom/packages/ink/lib/debugger/breakpoints.js:77:16
    at TextEditor.observeGrammar (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:7983)
    at file:///C:/Users/cnelias/.atom/packages/ink/lib/debugger/breakpoints.js:75:24
    at Workspace.observeTextEditors (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:428422)
    at new BreakpointManager (file:///C:/Users/cnelias/.atom/packages/ink/lib/debugger/breakpoints.js:74:34)
    at Object.activate (file:///C:/Users/cnelias/.atom/packages/julia-client/lib/runtime/debugger.js:30:17)
    at Object.consumeInk (file:///C:/Users/cnelias/.atom/packages/julia-client/lib/runtime.coffee:33:11)
    at Object.consumeInk (file:///C:/Users/cnelias/.atom/packages/julia-client/lib/julia-client.coffee:120:7)
    at Provider.provide (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:14:1125283)
    at ServiceHub.provide (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3308382)
    at Package.activateServices (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3316668)
    at Package.activateNow (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3313644)
    at measure (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3312968)
    at Package.measure (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3310578)
    at activationPromise.activationPromise.Promise (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3312828)
    at new Promise (<anonymous>)
    at Package.activate (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3312771)
    at PackageManager.activatePackage (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:382554)
    at C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:940004
    at r (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:934610)
    at n (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:14:1128190)
    at ChildProcess.o.process.on.e (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:14:1128396)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)```

**Comment by togo59** [comment]
Once, when I had difficulties with Atom updates, I uninstalled Atom completely and wiped the `.config/Atom` folder. Then reinstalled everything I needed, which was uberJuno, Hydrogen and LaTeX support. Ink got installed as a dependency. That worked perfectly but I can't remember what the specific problem was. I'm just saying.

**Comment by aviatesk** [comment]
@johncwok the error seems to say you've probably installed ink for now. Just restart Atom and see whether it works.

**Comment by frawas** [comment]
> I released a new version of julia-client (as well as ink) a couple of minutes ago (which might or might not help with this issue). Can you all try the following steps again:
> 
> 1. Close _all_ Atom instances.
> 2. Open a terminal and type in `apm uninstall ink` and `apm uninstall julia-client`,
> 3. Re-install those packages with `apm install ink`, followed by `apm install julia-client`.
> 4. Open Atom.

Same problem with atom version 1.41 update. This solution worked perfectly.

**Comment by jsoule281** [comment]
I had the same problem as @kschertler, same version of atom - I am able to uninstall and reinstall both ink and julia-client successfully, however when I open atom i'm told:
Incompatible packages detected.

julia-client
The above packages are incompatible with the current version of Atom and have been deactivated. Juno will not work properly until they are rebuilt.

I can rebuild julia-client in terminal, but the error message persists.

**Comment by pfitzseb** [comment]
@jsoule281 What OS are you on?

**Comment by JobJob** [comment]
@pierre-haessig I think your issue is that python is calling Python 3 and (as the error message shows) gyp wants Python 2. 

I have resolved this issue in the past by editing `/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh` and replacing the (2) references to `python` with `python2` (which is an alias to my Python 2 executable)

**Comment by pfitzseb** [comment]
While that's true, @JobJob, there shouldn't ever be the need to build anything yourself. We *should* have binaries available for all relevant OS/Electron version possibilities (see [here](https://github.com/oznu/node-pty-prebuilt-multiarch/releases/tag/v0.9.0)).

Atom version 1.40.0 had an issue where `apm` wouldn't correctly set some environment variables so that the installer couldn't pick the right binary, but that was fixed in 1.40.1 and up. So yeah, not sure what's going on here.

**Comment by JobJob** [comment]
Sorry, to clarify, I was only addressing these comments: https://github.com/JunoLab/atom-julia-client/issues/642#issuecomment-545891088,  https://github.com/JunoLab/atom-julia-client/issues/642#issuecomment-547023470, that reported the following error when running `apm install julia-client`:

```
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.7.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
```

That is the error that my suggestion [above](https://github.com/JunoLab/atom-julia-client/issues/642#issuecomment-551112266) may fix. It's an [issue with apm](https://github.com/atom/apm/issues/179), nothing to do with Juno/Atom-Julia-Client

I only skimmed the rest of what's happening in this issue so, sorry for any confusion caused.

**Comment by jsoule281** [comment]
> @jsoule281 What OS are you on?

I am on Mojave 10.14.5. I'm on atom 1.41.0, and Julia 1.2. I have installed the latest releases of juno and julia-client but still get the same error message:
Incompatible packages detected.

julia-client
The above packages are incompatible with the current version of Atom and have been deactivated. Juno will not work properly until they are rebuilt.

On atom when I try and rebuild julia-client it fails. When I rebuild in the terminal using apm it appears to work, but doesn't work in atom, despite quitting atom, rebuilding, and then reopening atom.

**Comment by sdobber** [comment]
> I am on Mojave 10.14.5. I'm on atom 1.41.0, and Julia 1.2. I have installed the latest releases of juno and julia-client but still get the same error message:
> Incompatible packages detected.

Same problem here with Mojave 10.14.6, Atom 1.41.0 and Julia 1.2. None of the steps above help, even deleting all Atom packages and settings and trying to re-install everything from scratch still provokes the "Incompatible packages detected" error message.

**Comment by sdobber** [comment]
Update: What worked for me was that after uninstalling and reinstalling `ink` and `julia-client`, I needed to rebuild _all_ packages in Atom.

**Comment by mattcbro** [comment]
> I released a new version of julia-client (as well as ink) a couple of minutes ago (which might or might not help with this issue). Can you all try the following steps again:
> 
> 1. Close _all_ Atom instances.
> 2. Open a terminal and type in `apm uninstall ink` and `apm uninstall julia-client`,
> 3. Re-install those packages with `apm install ink`, followed by `apm install julia-client`.
> 4. Open Atom.

This worked for me,  except that I appear to have redo these steps every time I reboot my computer.  So the problem is still persisting somehow.

**Comment by pfitzseb** [comment]
> Actually as a clarification, every time I open a new project folder, I start getting julia-client package errors

What errors are you getting?

**Comment by sth4nth** [comment]
For Atom 1.44 with julia-client 0.12.2, this problem is gone.

**Comment by manroygood** [comment]
I am having this problem now with 

Atom    : 1.48.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

and 

julia-client 0.12.5

Uninstall/reinstall works fine from the terminal or within Atom, but then rerunning Atom returns the same error messages.

In addition to julia-client, I am getting the same error message for the package "script"

**Comment by mike9753** [comment]
I have now the same problem with 
Atom    : 1.63.1
Electron: 11.5.0
Chrome  : 87.0.4280.141
Node    : 12.18.3

i tried to reinstall ink what was sucessfull but i couldn't reinstall julia-client or other packages
